# Generated by Django 5.2.12 on 2026-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
